#!/usr/bin/env python3
"""Discriminating quality probe: does IQ3_S preserve the 122B's edge over the 35B?

DESIGN PRINCIPLE: the only meaningful signal is the 122B winning where the 35B loses.
  - too easy  -> both pass -> no signal (the M2 failure: 24/24 vs 24/24)
  - too hard  -> both fail -> no signal
  - in the gap-> 35B fails, healthy 122B passes. Only here can IQ3 damage show, as the 122B
                 failing to win and scoring toward the 35B instead of above it.
So the 35B is the CALIBRATION INSTRUMENT, not a sideshow: any item it aces is DISCARDED (it
didn't probe the gap). We filter empirically rather than hoping the items are hard enough.

GROUND TRUTH IS COMPUTED, NOT HAND-WRITTEN. Every item is generated by code that also solves it
(brute force / direct execution), so difficulty can be tuned freely without me becoming the error
source. A wrong answer key fails a correct model and would silently poison the verdict.

Usage:
  probe_discriminating.py gen                          -> write items.json (candidate pool)
  probe_discriminating.py run <url> <model> <tag> [n] [a:b]  -> score, append to scores_<tag>.jsonl
  probe_discriminating.py calibrate <tag>              -> keep only items the 35B failed -> gap.json
  probe_discriminating.py report                       -> 3-way table + verdict
"""
import sys, json, re, random, itertools, urllib.request, pathlib, collections, statistics

SCR = pathlib.Path("/tmp/claude-1000/-mnt-d-LMServer/284c36d2-a897-4f4c-9c73-764205ad0495/scratchpad")
SYS = "You are Qwen, created by Alibaba Cloud. You are a helpful assistant."

# ---------------------------------------------------------------- item generators
def gen_chain(rng, n_steps):
    """Long dependent arithmetic chain: one early slip propagates to a wrong final answer."""
    x = rng.randint(3, 19)
    desc = [f"Start with {x}."]
    for _ in range(n_steps):
        op = rng.choice(["mul", "add", "sub", "sq", "half"])
        if op == "mul":
            k = rng.randint(2, 7); x *= k; desc.append(f"Multiply by {k}.")
        elif op == "add":
            k = rng.randint(3, 40); x += k; desc.append(f"Add {k}.")
        elif op == "sub":
            k = rng.randint(3, 40); x -= k; desc.append(f"Subtract {k}.")
        elif op == "sq":
            if abs(x) > 60: continue
            x = x * x; desc.append("Square the result.")
        else:
            if x % 2 != 0: x += 1; desc.append("Add 1.")
            x //= 2; desc.append("Divide by 2.")
    prompt = " ".join(desc) + " Give ONLY the final integer, nothing else."
    return prompt, str(x)

def gen_trace(rng):
    """Code trace with state a smaller model tends to lose. Ground truth = actual execution."""
    a, b, c = rng.randint(2, 5), rng.randint(2, 6), rng.randint(7, 15)
    src = (
        "def f(n):\n"
        "    t, s = 0, []\n"
        "    for i in range(1, n + 1):\n"
        f"        if i % {a} == 0:\n"
        "            t += i * 2\n"
        "            s.append(i)\n"
        f"        elif i % {b} == 0:\n"
        "            t -= i\n"
        "            if s: t += s.pop()\n"
        "        else:\n"
        "            t += 1\n"
        f"    return t + len(s)\n\nprint(f({c}))"
    )
    ns = {}
    exec(src.replace(f"print(f({c}))", ""), ns)
    val = ns["f"](c)
    prompt = ("Trace this Python code exactly, step by step, and give ONLY the printed integer:\n\n"
              + src)
    return prompt, str(val)

def gen_schedule(rng, n):
    """Constraint satisfaction with a UNIQUE brute-forced solution.
    The 2-bit gate/up failure mode is dropping a constraint mid-solve -> high value."""
    people = ["Ana", "Ben", "Cara", "Dan", "Eli", "Fay"][:n]
    for _ in range(400):
        sol = list(range(n)); rng.shuffle(sol)
        pos = {p: sol[i] for i, p in enumerate(people)}
        cons, texts = [], []
        pairs = list(itertools.combinations(people, 2)); rng.shuffle(pairs)
        for (p, q) in pairs[:n]:
            if pos[p] < pos[q]:
                cons.append(lambda a, p=p, q=q: a[p] < a[q]); texts.append(f"{p} is scheduled before {q}.")
            else:
                cons.append(lambda a, p=p, q=q: a[q] < a[p]); texts.append(f"{q} is scheduled before {p}.")
        p0 = rng.choice(people)
        cons.append(lambda a, p0=p0, v=pos[p0]: a[p0] == v)
        texts.append(f"{p0} is in slot {pos[p0]+1}.")
        for (p, q) in pairs[n:n+2]:
            if abs(pos[p]-pos[q]) != 1:
                cons.append(lambda a, p=p, q=q: abs(a[p]-a[q]) != 1)
                texts.append(f"{p} and {q} are NOT in adjacent slots.")
        sols = []
        for perm in itertools.permutations(range(n)):
            a = {p: perm[i] for i, p in enumerate(people)}
            if all(c(a) for c in cons): sols.append(a)
            if len(sols) > 1: break
        if len(sols) == 1:
            rng.shuffle(texts)
            prompt = (f"{n} people are each assigned exactly one of slots 1..{n} (one person per slot).\n"
                      + "\n".join("- " + t for t in texts)
                      + f"\n\nThere is exactly one valid assignment. Give ONLY the slot number (1..{n}) "
                        f"for {people[0]}, as a single integer.")
            return prompt, str(sols[0][people[0]] + 1)
    return None

def gen_compose(rng, k):
    """Nested/conditional rules over a list; a smaller model collapses a branch."""
    nums = [rng.randint(2, 60) for _ in range(k)]
    def isprime(v):
        if v < 2: return False
        for d in range(2, int(v**0.5)+1):
            if v % d == 0: return False
        return True
    tot = 0
    for v in nums:
        if v > 30:
            if v % 2 == 0: tot += v // 2
            elif isprime(v): tot -= 3
            else: tot += 1
        else:
            if isprime(v): tot += v * 2
            elif v % 3 == 0: tot -= v
            else: tot += 0
    prompt = ("Apply these rules to each number in the list, in order, and sum the contributions.\n"
              "For each number v:\n"
              "  - If v > 30:\n"
              "      * if v is even, contribute v/2 (integer division)\n"
              "      * else if v is prime, contribute -3\n"
              "      * else contribute +1\n"
              "  - Otherwise (v <= 30):\n"
              "      * if v is prime, contribute v*2\n"
              "      * else if v is divisible by 3, contribute -v\n"
              "      * else contribute 0\n"
              f"\nList: {nums}\n\nGive ONLY the final total as a single integer.")
    return prompt, str(tot)

def gen_needle2(rng, n_sent):
    """Two separated facts that must be COMBINED. Single-needle passes on both models already."""
    a = rng.randint(100, 999); b = rng.randint(100, 999)
    f1 = f"The alpha register holds the value {a}."
    f2 = f"The beta register holds the value {b}."
    filler = [f"Log entry {i}: routine telemetry sample, nominal, no action required." for i in range(1, n_sent)]
    q = int(a) * 2 + int(b)
    i1, i2 = n_sent // 5, (4 * n_sent) // 5
    filler.insert(i1, f1); filler.insert(i2, f2)
    prompt = (" ".join(filler) +
              "\n\nQuestion: compute (alpha register value * 2) + (beta register value). "
              "Both values appear somewhere above. Give ONLY the final integer.")
    return prompt, str(q)

def gen_trace_hard(rng):
    """Nested loops + dict/list state mutation. Ground truth = actual execution."""
    a, b, c = rng.randint(2, 4), rng.randint(3, 5), rng.randint(9, 13)
    src = (
        "def f(n):\n"
        "    d, stack, t = {}, [], 0\n"
        "    for i in range(1, n + 1):\n"
        "        for j in range(1, i + 1):\n"
        f"            k = (i * j) % {a+3}\n"
        "            d[k] = d.get(k, 0) + j\n"
        f"            if j % {a} == 0:\n"
        "                stack.append(i - j)\n"
        f"            elif j % {b} == 0 and stack:\n"
        "                t += stack.pop()\n"
        "        if i % 2 == 0 and d:\n"
        "            t -= min(d.values())\n"
        "    return t + sum(d.values()) - len(stack)\n"
        f"\nprint(f({c}))"
    )
    ns = {}
    exec(src.replace(f"print(f({c}))", ""), ns)
    return ("Trace this Python code exactly and give ONLY the printed integer:\n\n" + src), str(ns["f"](c))

def gen_needle3(rng, n_sent):
    """THREE separated facts that must all be combined. Two-fact passed on both models."""
    a, b, c = rng.randint(100, 999), rng.randint(10, 99), rng.randint(2, 9)
    facts = [f"The alpha register holds the value {a}.",
             f"The beta register holds the value {b}.",
             f"The gamma coefficient is {c}."]
    filler = [f"Log entry {i}: routine telemetry sample, nominal, no action required." for i in range(1, n_sent)]
    for pos, fct in zip((n_sent // 7, (3 * n_sent) // 7, (6 * n_sent) // 7), facts):
        filler.insert(pos, fct)
    val = (a - b) * c
    prompt = (" ".join(filler) +
              "\n\nQuestion: compute (alpha register value - beta register value) * gamma coefficient. "
              "All three values appear somewhere above. Give ONLY the final integer.")
    return prompt, str(val)

def build_pool2():
    """TIER 2 — the 35B aced all 42 tier-1 items 2/2, so the ceiling was far too low.
    Crank every axis: longer chains, 7-8 person grids, deeper nesting, nested-loop traces,
    three-fact needles at ~100K."""
    rng = random.Random(777)
    items = []
    for n in (20, 26):
        for r in range(4):
            p, a = gen_chain(rng, n); items.append({"id": f"H_chain{n}_{r}", "cat": "chain", "prompt": p, "ans": a})
    for r in range(6):
        p, a = gen_trace_hard(rng); items.append({"id": f"H_trace_{r}", "cat": "trace", "prompt": p, "ans": a})
    for n in (7, 8):
        for r in range(5):
            g = gen_schedule(rng, n)
            if g: items.append({"id": f"H_sched{n}_{r}", "cat": "sched", "prompt": g[0], "ans": g[1]})
    for k in (26, 34):
        for r in range(4):
            p, a = gen_compose(rng, k); items.append({"id": f"H_comp{k}_{r}", "cat": "compose", "prompt": p, "ans": a})
    for r in range(4):
        p, a = gen_needle3(rng, 5600); items.append({"id": f"H_needle3_{r}", "cat": "needle3", "prompt": p, "ans": a})
    return items

def build_pool():
    rng = random.Random(20260715)
    items = []
    for n in (8, 10, 12):
        for r in range(4):
            p, a = gen_chain(rng, n); items.append({"id": f"chain{n}_{r}", "cat": "chain", "prompt": p, "ans": a})
    for r in range(8):
        p, a = gen_trace(rng); items.append({"id": f"trace_{r}", "cat": "trace", "prompt": p, "ans": a})
    for n in (5, 6):
        for r in range(5):
            g = gen_schedule(rng, n)
            if g: items.append({"id": f"sched{n}_{r}", "cat": "sched", "prompt": g[0], "ans": g[1]})
    for k in (10, 14):
        for r in range(4):
            p, a = gen_compose(rng, k); items.append({"id": f"comp{k}_{r}", "cat": "compose", "prompt": p, "ans": a})
    for r in range(4):
        p, a = gen_needle2(rng, 2500); items.append({"id": f"needle2_{r}", "cat": "needle2", "prompt": p, "ans": a})
    return items

# ---------------------------------------------------------------- scoring
def check(ans, text):
    """Strict: the ground-truth integer must appear as the last integer in the reply."""
    nums = re.findall(r"-?\d+", text.replace(",", ""))
    return bool(nums) and nums[-1] == str(ans)

def ask(base, model, prompt, temp=0.6):
    body = json.dumps({"model": model,
                       "messages": [{"role": "system", "content": SYS}, {"role": "user", "content": prompt}],
                       # per-model floor from M2's 'empty answer' FAIL: this model thinks LONG.
                       # a truncated chain scores wrong for the wrong reason and poisons the result.
                       "max_tokens": 16000,
                       "temperature": temp, "top_p": 0.95, "top_k": 20, "stream": False}).encode()
    r = urllib.request.Request(base + "/v1/chat/completions", data=body,
                               headers={"Content-Type": "application/json"})
    d = json.load(urllib.request.urlopen(r, timeout=1800))
    ch = d["choices"][0]
    return (ch["message"].get("content") or ""), ch.get("finish_reason")

def cmd_run(base, model, tag, n, sl):
    items = json.load(open(SCR / "items.json"))
    # Only score-runs filter to the gap-set. Calibration runs (tag starts with "calib") must see
    # the FULL pool -- filtering them by a previous, possibly EMPTY gap.json silently runs zero
    # items and prints nothing, which looks like success.
    if pathlib.Path(SCR / "gap.json").exists() and not tag.startswith("calib"):
        keep = set(json.load(open(SCR / "gap.json")))
        items = [i for i in items if i["id"] in keep]
    if sl:
        a, b = sl.split(":"); items = items[int(a):int(b)]
    out = open(SCR / f"scores_{tag}.jsonl", "a")
    for it in items:
        res, trunc = [], 0
        for _ in range(n):
            try:
                c, fin = ask(base, model, it["prompt"])
            except Exception as e:
                res.append(None); print(f"  {it['id']:<12} ERR {type(e).__name__}"); continue
            if fin == "length": trunc += 1
            res.append(bool(check(it["ans"], c)))
        hits = sum(1 for x in res if x)
        print(f"  {it['id']:<12} {hits}/{len(res)}  ans={it['ans']:<8} trunc={trunc}")
        out.write(json.dumps({"id": it["id"], "cat": it["cat"], "ans": it["ans"],
                              "res": res, "hits": hits, "n": len(res), "trunc": trunc}) + "\n")
        out.flush()

def cmd_calibrate(tag):
    rows = [json.loads(l) for l in open(SCR / f"scores_{tag}.jsonl")]
    best = {}
    for r in rows: best[r["id"]] = r          # last wins
    gap = [r["id"] for r in best.values() if r["hits"] < r["n"]]   # 35B failed or was inconsistent
    aced = [r["id"] for r in best.values() if r["hits"] == r["n"]]
    json.dump(gap, open(SCR / "gap.json", "w"))
    print(f"  candidates : {len(best)}")
    print(f"  35B ACED   : {len(aced)}  -> DISCARDED (not in the gap, would prove nothing)")
    print(f"  35B FAILED : {len(gap)}  -> the gap-set")
    bycat = collections.Counter(best[i]["cat"] for i in gap)
    print(f"  gap-set by category: {dict(bycat)}")
    if len(gap) < 10:
        print("\n  !! FEWER THAN 10 GAP ITEMS. The 35B is not failing enough to calibrate against.")
        print("     That is itself a finding — see the 'honest failure mode' in the brief.")
    return gap

if __name__ == "__main__":
    cmd = sys.argv[1]
    if cmd == "gen2":
        items = build_pool2()
        json.dump(items, open(SCR / "items.json", "w"), indent=1)
        print(f"TIER-2 pool: {len(items)} items")
        print(collections.Counter(i["cat"] for i in items))
    elif cmd == "gen":
        items = build_pool()
        json.dump(items, open(SCR / "items.json", "w"), indent=1)
        print(f"pool: {len(items)} items")
        print(collections.Counter(i["cat"] for i in items))
    elif cmd == "run":
        base, model, tag = sys.argv[2], sys.argv[3], sys.argv[4]
        n = int(sys.argv[5]) if len(sys.argv) > 5 else 3
        sl = sys.argv[6] if len(sys.argv) > 6 else ""
        cmd_run(base, model, tag, n, sl)
    elif cmd == "calibrate":
        cmd_calibrate(sys.argv[2])
